### PR TITLE
mapKeys

### PR DESCRIPTION
**Pull request by liambaloh**
Adds the companion function to map(..): mapKeys(..) intended for the purpose of rekeying the Map.

This is the specific use case this solves for me:

Old code:
```php
    private function LoadCategoriesFromDatabase(): array
    {
        $categoryDbInterface = CategoryDbInterface::Create($this->Database);
        $categoryTableRows = $categoryDbInterface->SelectAll();

        $categoryDatums = array();
        foreach ($categoryTableRows as $i => $categoryTableRow) {
            $categoryDatums[$categoryTableRow->Id] = CategoryDatum::FromCategoryTableRow($categoryTableRow);
        }

        return $categoryDatums;
    }
```

New code:
```php
    private function LoadCategoriesFromDatabase(): MapOfCategoryDatum
    {
        $categoryDbInterface = CategoryDbInterface::Create($this->Database);
        $categoryTableRows = $categoryDbInterface->SelectAll();

        $categoryDatums = $categoryTableRows
            ->map(fn(CategoryTableRow $categoryTableRow) => CategoryDatum::FromCategoryTableRow($categoryTableRow))
            ->CastToMapOfCategoryDatum()
            ->mapKeys(fn(CategoryDatum $categorydatum) => $categorydatum->Id);

        return $categoryDatums;
    }
```

The issue being that the array returned by `$categoryDbInterface->SelectAll();` isn't keyed by the category Id, so instead while `map(..)` handles the conversion of `CategoryTableRow` objects into `CategoryDatum` objects, keying remains as meaningless as what `$categoryDbInterface->SelectAll();` returned. The new `mapKeys(..)` function addresses this by rekeying all entries to be category Ids, which is what functions that call `LoadCategoriesFromDatabase()` expect.

Please let me know if this is something desired in this library. As before I'm only sharing functions I found useful or necessary. If there's an alternate way to achieve this I haven't found it, so making a more obvious way to achieve this might be a good idea irrespective of whether this pull request ends up being accepted or not.

Please ignore the `CastToMapOfCategoryDatum()`, it's there for type hinting

Thanks

### CODE REVIEW

**Comment by aimeos** [comment]
The `Map::col()` method does the same, the `CategoryDatum` objects only need a magic `__get()` method.

**Comment by liambaloh** [comment]
You're correct, the following code works too:

```php

private function LoadCategoriesFromDatabase(): MapOfCategoryDatum
{
  $categoryDbInterface = CategoryDbInterface::Create($this->Database);

  return $categoryDbInterface->SelectAll()
    ->map(fn(CategoryTableRow $categoryTableRow) => CategoryDatum::FromCategoryTableRow($categoryTableRow))
    ->CastToMapOfCategoryDatum()
    ->col(null, "Id");
}

/../

class CategoryDatum
{
  public string $Id;

  /../

  public function __get(string $name): string
  {
      return $this[$name];
  }
}
```

However this has downsides: I need to implement a `__get($string)` method in a class which I may not be able to modify cleanly (retrieved from a dependency, for example) and values passed through `__get($name)` seem to lose their usage information (and likely type - though in this case all the fields of `CategoryDatum` are of type `string`, so I can safely declare the return type of `__get(..)` to `string`):

image
image


vs with `mapKeys(..)`:
image
image

I'll be sticking with `mapKeys(..)` in my source, though if you feel it unnecessary for the main library then feel free to close this pull request. Also `rekey(..)` or `reindex(,,)` are some alternate names for this method if `mapKeys(..)` doesn't sound right

**Comment by aimeos** [comment]
A viable way would be to allow closures as parameters for `col()` to avoid having several methods doing roughly the same only with different parameters.

You can always add custom methods that are useful for your project:
https://php-map.org/#custom-methods

**Comment by liambaloh** [comment]
I'm personally not a big fan of using `mixed` parameters or implied parameter unions, at least not before PHP 8 becomes the lowest commonly supported version, because 💚 'compile'-time errors. Though as `col(..)` is at its heart a library re-implementation of php's `array_column(..)` function, it might make sense to keep it consistent with what a developer expects from `array_column(..)`, and not overloading it with similar, but not identical functionality. Though that's just thinking out loud, it's your call.

**Comment by aimeos** [comment]
`rekey()` might be a better name for your new method because shorter and describes exactly what it does. Then, there should be no objections any more

**Comment by liambaloh** [comment]
Sounds good, function renamed 🙂

**Comment by aimeos** [comment]
Thanks a lot!

**Pull request merged**
